### PR TITLE
Fix browser incompatibilities

### PR DESCRIPTION
**Pull request by wilsonplau**
SSIA

### CODE REVIEW

**Review by T-Damer — COMMENTED** [review]
It behaves like this on chrome mostly, it scrolls one time and stops

**Review by T-Damer — COMMENTED** [review]
okay, I didn't fix it, let's switch to library or something

**Comment by wilsonplau** [comment]
Yep, replaced with `react-slick`. More complicated than I thought it would be.

**Review by T-Damer — APPROVED** [review]
lfg

**Pull request merged**
